version: '2'
services:
  discipleship:
    build: "Discipleship"
    container_name: "Discipleship"
    environment:
     - ENVIRONMENT=PRODUCTION
     - AWS_ACCESS_KEY_ID=AKIAJYNWGNXVDU2GOOWQ
     - AWS_SECRET_ACCESS_KEY=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
     - AWS_DEFAULT_REGION=us-east-1
    ports:
     - "5000:5000"
    links:
     - mongodb
  presentation:
    build: "Presentation"
    container_name: "Presentation"
    environment:
     - ENVIRONMENT=PRODUCTION
    ports:
     - "5001:5000"
    links:
     - mongodb
  academy:
    build: "Academy"
    container_name: "Academy"
    environment:
     - ENVIRONMENT=PRODUCTION
     - AWS_ACCESS_KEY_ID=AKIAJWOI3WAXC2V4NKLQ
     - AWS_SECRET_ACCESS_KEY=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
     - AWS_DEFAULT_REGION=us-east-1
    ports:
     - "5002:5000"
    links:
     - mongodb
  mongodb:
    container_name: "mongodb"
    image: "mongo:latest"
    volumes:
    - ~/.mongo/db/:/data/db/
volumes:
    mongodb: