version: '2'
services:
  discipleship:
    build: "Discipleship"
    container_name: "Discipleship"
    environment:
     - ENVIRONMENT=PRODUCTION
    ports:
     - "5000:5000"
    links:
     - mongodb
  presentation:
    build: "Presentation"
    container_name: "Presentation"
    environment:
     - ENVIRONMENT=PRODUCTION
    ports:
     - "5001:5000"
    links:
     - mongodb
  mongodb:
    container_name: "mongodb"
    image: "mongo:latest"
    volumes:
    - ~/.mongo/db/:/data/db/
volumes:
    mongodb: